# Generated by Django 4.2 on 2026-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersession_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersession',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='release_after_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
