# Generated by Django 4.2 on 2026-03-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersession_paid_at_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('coupon_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('split_count', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='orders.ordersession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
