# Generated by Django 4.2 on 2026-03-02 10:27

import apps.tables.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='verification_pin',
            field=models.CharField(default=apps.tables.utils.generate_table_pin, max_length=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_token',
            field=models.CharField(default=apps.tables.utils.generate_qr_token, editable=False, max_length=64, unique=True),
        ),
    ]
