# Generated by Django 4.2 on 2026-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_verification_pin_alter_table_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('active', 'Active'), ('paid', 'Paid'), ('reserved', 'Reserved')], default='free', max_length=20),
        ),
    ]
