# Generated by Django 4.2 on 2026-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
